version: "3.7"

services:
  cp-helper-backend:
    ports:
    - "5005:5005"
    environment:
      - JVM_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005

  kafka-connect:
    environment:
      CONNECT_LOG4J_ROOT_LOGLEVEL: DEBUG
